// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhongweixian.grpc.user.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
