// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public interface StromRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhongweixian.grpc.user.StromRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string request = 1;</code>
   */
  String getRequest();
  /**
   * <code>optional string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
