// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public interface StromResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhongweixian.grpc.user.StromResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string response = 1;</code>
   */
  String getResponse();
  /**
   * <code>optional string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
