// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhongweixian_grpc_user_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zhongweixian_grpc_user_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhongweixian_grpc_user_UserLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zhongweixian_grpc_user_UserLoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhongweixian_grpc_user_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zhongweixian_grpc_user_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhongweixian_grpc_user_StromRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zhongweixian_grpc_user_StromRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhongweixian_grpc_user_StromResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zhongweixian_grpc_user_StromResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nUser.proto\022\032org.zhongweixian.grpc.user" +
      "\032\033google/protobuf/empty.proto\032\036google/pr" +
      "otobuf/wrappers.proto\"2\n\014LoginRequest\022\020\n" +
      "\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\232\001\n\021Us" +
      "erLoginResponse\022\013\n\003uid\030\001 \001(\005\022\020\n\010username" +
      "\030\002 \001(\t\022.\n\004role\030\003 \001(\0162 .org.zhongweixian." +
      "grpc.user.Role\0226\n\010workType\030\004 \001(\0162$.org.z" +
      "hongweixian.grpc.user.WorkType\"-\n\014UserRe" +
      "sponse\022\013\n\003uid\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\"\037\n" +
      "\014StromRequest\022\017\n\007request\030\001 \001(\t\"!\n\rStromR",
      "esponse\022\020\n\010response\030\001 \001(\t*\033\n\004Role\022\t\n\005adm" +
      "in\020\000\022\010\n\004user\020\001*,\n\010WorkType\022\n\n\006mobile\020\000\022\013" +
      "\n\007webcall\020\001\022\007\n\003sip\020\0022\253\002\n\013UserService\022Q\n\007" +
      "getUser\022\034.google.protobuf.StringValue\032(." +
      "org.zhongweixian.grpc.user.UserResponse\022" +
      "f\n\tUserLogin\022(.org.zhongweixian.grpc.use" +
      "r.LoginRequest\032-.org.zhongweixian.grpc.u" +
      "ser.UserLoginResponse0\001\022a\n\006WeChat\022(.org." +
      "zhongweixian.grpc.user.StromRequest\032).or" +
      "g.zhongweixian.grpc.user.StromResponse(\001",
      "0\001B\024B\020UserServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_org_zhongweixian_grpc_user_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_zhongweixian_grpc_user_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zhongweixian_grpc_user_LoginRequest_descriptor,
        new String[] { "Username", "Password", });
    internal_static_org_zhongweixian_grpc_user_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_zhongweixian_grpc_user_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zhongweixian_grpc_user_UserLoginResponse_descriptor,
        new String[] { "Uid", "Username", "Role", "WorkType", });
    internal_static_org_zhongweixian_grpc_user_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_zhongweixian_grpc_user_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zhongweixian_grpc_user_UserResponse_descriptor,
        new String[] { "Uid", "Username", });
    internal_static_org_zhongweixian_grpc_user_StromRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_zhongweixian_grpc_user_StromRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zhongweixian_grpc_user_StromRequest_descriptor,
        new String[] { "Request", });
    internal_static_org_zhongweixian_grpc_user_StromResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_zhongweixian_grpc_user_StromResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zhongweixian_grpc_user_StromResponse_descriptor,
        new String[] { "Response", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
