// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhongweixian.grpc.user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
