// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.zhongweixian.grpc.user;

public interface UserLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhongweixian.grpc.user.UserLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional .org.zhongweixian.grpc.user.Role role = 3;</code>
   */
  int getRoleValue();
  /**
   * <code>optional .org.zhongweixian.grpc.user.Role role = 3;</code>
   */
  Role getRole();

  /**
   * <code>optional .org.zhongweixian.grpc.user.WorkType workType = 4;</code>
   */
  int getWorkTypeValue();
  /**
   * <code>optional .org.zhongweixian.grpc.user.WorkType workType = 4;</code>
   */
  WorkType getWorkType();
}
